name: woogoods
description: A new Flutter project.

publish_to: 'none'
#version: - 1.0.2+4
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  awesome_dialog: ^2.1.1
  google_fonts: ^2.1.0
  flutter_staggered_grid_view: ^0.6.1
  cached_network_image: ^3.2.1
  http: ^0.13.3
  shared_preferences: ^2.0.7
  intl: ^0.17.0
  flutter_svg:
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  animations: ^2.0.2
  like_button: ^2.0.3
  scrollable_list_tabview: ^0.2.0-nullsafety
  vertical_scrollable_tabview: ^0.0.2
  snapping_sheet: ^3.1.0
  #local database
  sqflite: ^2.0.1
  #permission_handler: ^8.3.0
  #country and code picker
  country_code_picker: ^2.0.2
  #pin code filed
  pin_code_fields: ^7.3.0
  #order stepper
  timelines: ^0.1.0
  timeline_tile: ^2.0.0
  #styling dotted underline:
  dotted_line: ^3.1.0
  dotted_border: ^2.0.0+1
  #card package
  flutter_credit_card: ^3.0.1
  awesome_card: ^1.1.5
  #Contry, State, City Picker
  csc_picker: ^0.2.6
  #Scoll Tab with controller
  scroll_to_index: ^2.1.0
  rect_getter: ^1.0.0
  #Image picker form storage
  image_picker: ^0.8.4+4
  url_launcher: ^6.0.17
  share_plus: ^4.0.10+1
  #social_login
  google_sign_in: ^5.4.1
  flutter_facebook_auth: ^4.4.1
  #firebase
  firebase_messaging: ^12.0.3
  firebase_core: ^1.21.0
  #onesignal notifications
  onesignal_flutter: ^3.3.0
  new_version: ^0.3.0
  #tawk live chat
  flutter_tawk: any
  modal_bottom_sheet: ^2.0.1
  path_provider: ^2.0.11
  path: ^1.8.1
  #payment gateway
  flutter_stripe: ^4.0.0
  flutter_sslcommerz: ^2.1.1-nullsafety.0
  razorpay_flutter: ^1.3.2
  flutter_braintree: ^2.3.1
  paytm_allinonesdk: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  #adaptive_icon_background: "assets/images/bg.png"
  #adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/



